<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Tomás Péndola y Benjamin Sepulveda">

<title>Percepcion de Inseguridad Segun Orientacion Politica</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Trabajo Final Pendola y Sepulveda_files/libs/clipboard/clipboard.min.js"></script>
<script src="Trabajo Final Pendola y Sepulveda_files/libs/quarto-html/quarto.js"></script>
<script src="Trabajo Final Pendola y Sepulveda_files/libs/quarto-html/popper.min.js"></script>
<script src="Trabajo Final Pendola y Sepulveda_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Trabajo Final Pendola y Sepulveda_files/libs/quarto-html/anchor.min.js"></script>
<link href="Trabajo Final Pendola y Sepulveda_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Trabajo Final Pendola y Sepulveda_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Trabajo Final Pendola y Sepulveda_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Trabajo Final Pendola y Sepulveda_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Trabajo Final Pendola y Sepulveda_files/libs/bootstrap/bootstrap-1bc8a17f135ab3d594c857e9f48e611b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="Trabajo Final Pendola y Sepulveda_files/libs/tabwid-1.1.3/tabwid.css" rel="stylesheet">

<script src="Trabajo Final Pendola y Sepulveda_files/libs/tabwid-1.1.3/tabwid.js"></script>



</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Percepcion de Inseguridad Segun Orientacion Politica</h1>
<p class="subtitle lead">Estadistica IV</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor/a</div>
    <div class="quarto-title-meta-contents">
             <p>Tomás Péndola y Benjamin Sepulveda </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Fecha de publicación</div>
    <div class="quarto-title-meta-contents">
      <p class="date">29 de mayo de 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="índice" class="level1">
<h1>Índice</h1>
<ol type="1">
<li>Introducción ……………….. 1</li>
<li>Marco Teórico ……………… 2</li>
<li>Metodología ……………….. 3</li>
<li>Análisis Factorial Exploratorio … 4</li>
<li>Análisis de Conglomerados …….. 5</li>
<li>Análisis de Correspondencias Múltiples … 6</li>
<li>Análisis Conjunto ………….. 7</li>
<li>Conclusiones ………………. 8</li>
<li>Bibliografía ………………. 9</li>
</ol>
</section>
<section id="introducción" class="level1">
<h1>Introducción</h1>
<p>En el último tiempo debido a diversos factores, como escándalos dentro del gobiernos, como el caso fundaciones y sobretodo debido al clima electoral chileno se tiene de hablar mucho sobre la confianza que se tiene sobre las diversas instituciones e incluso se llega a comparar con otros países, donde gobiernan partidos o gobernantes de corte más autoritario y cercanos a la derecha, entonces surge la pregunta de ¿Qué tanta diferencia existe en la confianza institucional entre países dirigidos por presidente de derecha y de izquierda en América Latina?</p>
<p>La investigación usará la base de datos de Latinobarómetro en su última oleada, la de 2024 para ser específicos, se centra en comparar la confianza institucional usando las variables, “P14ST.E”, que mide la Confianza en el gobierno, “P14ST.F”, que mide la Confianza en el poder judicial, “P14ST.G” , que mide Confianza en los partidos políticos, “P14STGBS.B”, que mide la Confianza en la policía, junto a las variables de EDAD, REEDUC.1 que mide la educación del encuestado, e IDENPA que identifica el país de quien responde la encuesta. Usando estas variables estableceremos que nuestro objetivo general es describir la diferencia entre los países dirigidos por presidentes de izquierda y presidentes de derecha, bajo los objetivos específicos siendo:</p>
<ul>
<li><p>Caracterizar los patrones de agrupamiento de países según perfiles de confianza institucional y su relación con la orientación política de sus gobiernos</p></li>
<li><p>Analizar las asociaciones entre orientación gubernamental y niveles específicos de confianza institucional mediante análisis de correspondencias</p></li>
</ul>
<p>Ademas como hipótesis central tenemos que:</p>
<ul>
<li>Países con presidentes de Derecha podrían mostrar mayor confianza en el gobierno a diferencia de Países con presidentes de Izquierda que mostraron índices más bajos</li>
</ul>
<p>“P14ST.K”, que mide la Confianza en los medios de comunicación y la variable “P12STGBS.A” que mide la Satisfacción con la Democracia (variables que se podrían eliminar)</p>
<p>Finalmente este informe se estructura en cuatro secciones principales: primero, se presenta el marco teórico sobre confianza institucional; segundo, se detalla la metodología y tratamiento de datos; tercero, se aplican tres modelos estadísticos (AFE, clustering y ACM) para analizar los patrones de confianza; finalmente, se discuten los hallazgos y sus implicancias para la comprensión de la legitimidad política en América Latina.</p>
<p>FALTA PONER EL RESUMEN DE TODO LO QUE SE VE DENTRO DEL INFORME</p>
</section>
<section id="marco-teórico" class="level1">
<h1>Marco Teórico</h1>
<p>Para proceder con el análisis en primera instancia se tiene que entender que es la “confianza institucional” , autores como Morales (2008) y Campo Garcia (2018) usando a Easton (1975) establecen que:</p>
<p>“La confianza hacia las instituciones puede ser entendida como una forma de apoyo”difuso” al régimen político expresado en actitudes favorables a la democracia, o como un respaldo “específico” según el desempeño y los resultados alcanzados por el gobierno o las autoridades políticas (Morales, 2008, p.4)&nbsp;</p>
<p>Coincidiendo a grandes rasgos con Estella de Noriega (2020) que reconoce que la confianza institucional puede llegar a detectar sobre qué es la confianza en instituciones llega a entender, siendo que las divide en 2 partes, la primera tiene que con el sistema jurídico que es la que menos atención a llegado a recibir y la segunda sobre el gobierno central, que si ha tenido el foco principal, pues es la que Latinoamérica ha desarrollado para mostrar que la confianza institucional es baja pero a pesar de ello el miso Estella de Noriega (2020 )al citar a Algan reconoce “se necesita más investigación sobre la cuestión de la confianza institucional” (2018: 312).</p>
<p>igualmente Campos Garcia, expande más, para la autora la capacidad de una confianza institucional positiva es parte de un elemento más grande siento este el concepto de buen gobierno, que coincidiendo con lo que Morales (2020) establece como el punto contrario a lo que produce la desconfían siendo esta una crisis de legitimidad, que puede producir lo que en Chile terminó siendo en el 2018 el estallido social.</p>
<p>Pero aparte de ellos, todos los autores componen que la confianza institucional puede ser dividida en dimensiones como la confianza en las fuerzas armadas o de orden, en el poder judicial, parlamento, gobierno, presidente e incluso los partidos políticos, entre otras dimensiones. Precisamente la razón por la cual se ha decido trabajar la variable de la Satisfacción de la Democracia. Igualmente Morales (2020) considera que ante la una baja confianza en las instituciones de orden público como carabineros en Chile, genera un distanciamiento que si se suma al creciente distanciamiento de los partidos políticos será el culmine de lo que se conoce como “malestar con la representación democrática”, que se suma a las percepciones negativas ante la desigualdad y los conflictos entre ricos y pobres. Siendo esto muy contrario a las mismas declaraciones del mismo Morales en (2008) donde en Chile</p>
<p>es posible distinguir entre las instituciones de orden y jerarquizadas como las Fuerzas Armadas y la Iglesia, e instituciones de conflicto como los partidos y Congreso. Las primeras, por cierto, presentan niveles de confianza significativamente más elevados (p.4)</p>
<p>Finalmente como se ha trabajar con la base de datos del Latinobarómetro, se busca trabajar con cierto países, específicamente con Chile, Argentina, Perú y El Salvador, esta selección se realiza bajo una condicionante de Torcal y Bargsted, que especifican que Latinoamérica sufre algo llamado el “giro hacia la izquierda” donde ciertos países de Latinoamerica sufren una mejora considerable dentro de lo que es su confianza en las instituciones de gobierno, como el presidente o el parlamento (2015), según los autores este crecimiento ocurre de manera constante hasta el 2013 donde se destacan finalmente esto llega a ocurrir debido a dos factores que son:</p>
<p>La actuación conjunta de ciertas reformas institucionales y la lucha directa contra la corrupción y la desigualdad (especialmente en América Latina), serían suficientes para mejorar la situación de muchos de los países con respecto de los niveles más bajos de confianza en las instituciones representativas (Torcal y Bargsted, 2015, p.29)</p>
<p>Hoy en día se puede hablar más posiblemente de un giro contrario pues ciertos países de Latinoamerica han decidido votar hacia la derecha y muchos países como los que se han decido trabajar en este estudio como El Salvador con Nayib Bukele o Argentina con Javier Milei, pero otros como Chile con Gabriel Boric o Perú con José Jeri, el giro hacia la izquierda de Torcal y Bargsted, cosa que lleva a preguntarse entonces a qué instituciones estos países que han girado hacia la derecha tienden a sentir más confianza y si las instituciones de países que se han mantenido dentro del giro a la izquierda aún sienten una gran confianza hacia las instituciones del gobierno central.</p>
</section>
<section id="metodología" class="level1">
<h1>Metodología</h1>
<p>En primera instancia para el inicio del trabajo se usaron una serie de “librerías” de R</p>
<p>Como se ha establecido antes se ha de trabajar la base de datos entregados por la base datos del Latinobarometro con ciertas variables específicamente;</p>
<div class="cell">
<pre><code>## Invalid date string (length=9): 17 032 25</code></pre>
</div>
<p>Variables de Confianza:</p>
<ul>
<li><p>P14ST.E, Confianza en el Gobierno</p></li>
<li><p>P14ST.F, Confianza en el Poder Judicial</p></li>
<li><p>P14ST.G, Confianza en los Partidos Políticos</p></li>
<li><p>P14STGBS.B, Confianza en la policía</p></li>
<li><p>P14ST.K, Confianza en los Medios de Comunicación</p></li>
<li><p>P12STGBS.A, Satisfacción con la Democracia</p></li>
</ul>
<p>Y la variable de control para el resto del estudio:</p>
<ul>
<li>IDENPA, País del Encuestado</li>
</ul>
<p>Antes de proceder plenamente con el análisis se realización una serie de tratamientos para las distintas variables, primero se limito la variable IDENPA</p>
<p>Para los propósitos del trabajo se limito a 4 países, 2 cuya orientación fuera de Izquierda, que son el 152 que es Chile y el 604 siendo este Perú, por otra parte se escogió 2 cuya orientación fuera de derecha, que son el 32 siendo Argentina y el 222 que es El Salvador.</p>
<p>Como paso siguiente se renombraron las variables de confianza para su mas fácil identificación</p>
<p>Quedando las variables de confianza como:</p>
<ul>
<li><p>P14ST.E = conf_gobierno</p></li>
<li><p>P14ST.F = conf_poder_judicial</p></li>
<li><p>P14ST.G = conf_partidos</p></li>
<li><p>P14STGBS.B = conf_policia</p></li>
<li><p>P14ST.K = conf_medios</p></li>
<li><p>P12STGBS. = Asatisf_democracia</p></li>
</ul>
<p>Ademas se opto por tratar directamente los datos perdidos (NA) de estas variables que eran reconocidos como -1 y -2</p>
<p>Seguido se crea una base separada del resto que únicamente contenga la base datos limpia sin los Na y renombrar las variable IDENPA, para que sea categórica y los países pasen de ser códigos numéricos a nombres directamente</p>
<p>Ademas se opto generar otra base datos que contuviera las variables de confianza en formato cualitativo</p>
<p>Para los propósitos de este trabajo se han de trabajar 3 modelos siendo todos estos modelos exploratorios, el primero de ellos se trata de un Modelo de Análisis Factorial Exploratorio (AFE), este se escoge a modo de exploración de la base de datos con la que se ha trabajar, y ver las variables latentes que pueden explicar en como se agrupan las variables que miden la confianza a lo largo de las instituciones gubernamentales. El segundo es un Análisis de Conglomerados o Cluster para ver como se agrupan las variables de confianza según los países elegidos. Finalmente como tercer modelo se hizo un Análisis de Correspondencias Múltiples para finalmente ver como los países seleccionados se agrupan en que sectores y que variables de confianza se encuentran mas cerca de cual país.</p>
<section id="analisis-factorial-exploratorio-efa" class="level2">
<h2 class="anchored" data-anchor-id="analisis-factorial-exploratorio-efa">Analisis Factorial Exploratorio (EFA)</h2>
<p>El Análisis Factorial Exploratorio es un análisis que usa variables cuantitativas de variables Likert para medir variables latentes, estas ultimas no son observables usualmente dentro de las ciencias sociales, ergo la necesidad de medir si es que existen o no.</p>
<p>Como primer Paso se seleccionaron las variables para el EFA</p>
<p>Seguido de ello se realizaron los test de Kaiser-Meyer-Olkin o bien llamdo KM0 y el test de esfericidad de Bartlett, estos test se realizan para dos cosas en especifico, el KM0 mide la proporcion de la varianza de las variables y permiten determinar si estas son o no factorizables, dependiendo de los resultados que pueda mostrar estos se pueden considerar aceptables para su uso o no, entre un rango de 0.90 y 0.50 es aceptable para su uso. Mientras el test de Esfericidad de Bartlett es una prueba de hipótesis de que no hay correlaciones significativas entre las variables. sera significativo si es que el p &lt; 0.05, sugiere que el análisis factorial es apropiado.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Trabajo-Final-Pendola-y-Sepulveda_files/figure-html/Determinar%20el%20Numero%20de%20Factores-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Trabajo-Final-Pendola-y-Sepulveda_files/figure-html/Determinar%20el%20Numero%20de%20Factores-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<pre><code>## Parallel analysis suggests that the number of factors =  3  and the number of components =  NA</code></pre>
</div>
<p>Seguido decidimos producir 2 gráficos para determinar el numero de factores a utilizar, siendo este el gráfico de sedimentacion o coloquialmente conocido como el gráfico del codo debido a que marca el numero de factores cuando se quiebra la recta y se regulariza la recta y el otro es el gráfico de análisis paralelo que ajusta mejor la recta para mostrar si es que puede mas factores posibles</p>
<div class="cell">
<pre><code>## Factor Analysis using method =  minres
## Call: fa(r = variables_afe, nfactors = 3, rotate = "varimax", fm = "minres")
## Standardized loadings (pattern matrix) based upon correlation matrix
##                     item   MR1   MR2   MR3    h2      u2  com
## conf_gobierno          1 0.947 0.190 0.251 0.995 0.00455 1.23
## satisf_democracia      6 0.434 0.148 0.288 0.293 0.70655 2.01
## conf_partidos          3 0.229 0.936 0.245 0.989 0.01103 1.26
## conf_policia           4 0.247 0.091 0.589 0.416 0.58352 1.39
## conf_medios            5 0.139 0.181 0.472 0.275 0.72478 1.48
## conf_poder_judicial    2 0.439 0.349 0.457 0.523 0.47662 2.87
## 
##                         MR1   MR2   MR3
## SS loadings           1.410 1.098 0.985
## Proportion Var        0.235 0.183 0.164
## Cumulative Var        0.235 0.418 0.582
## Proportion Explained  0.404 0.314 0.282
## Cumulative Proportion 0.404 0.718 1.000
## 
## Mean item complexity =  1.7
## Test of the hypothesis that 3 factors are sufficient.
## 
## df null model =  15  with the objective function =  1.583 with Chi Square =  6839.187
## df of  the model are 0  and the objective function was  0 
## 
## The root mean square of the residuals (RMSR) is  0.001 
## The df corrected root mean square of the residuals is  NA 
## 
## The harmonic n.obs is  4324 with the empirical chi square  0.079  with prob &lt;  NA 
## The total n.obs was  4324  with Likelihood Chi Square =  0.167  with prob &lt;  NA 
## 
## Tucker Lewis Index of factoring reliability =  -Inf
## Fit based upon off diagonal values = 1
## Measures of factor score adequacy             
##                                                     MR1   MR2    MR3
## Correlation of (regression) scores with factors   0.984 0.982  0.704
## Multiple R square of scores with factors          0.968 0.964  0.495
## Minimum correlation of possible factor scores     0.936 0.928 -0.010</code></pre>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Trabajo-Final-Pendola-y-Sepulveda_files/figure-html/Análisis%20factorial%20exploratorio-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Con ello se realiza el análisis factorial, escogiendo ajustar por el numero de factores recomendados por el gráfico de sedimento y el análisis paralelo. Y se analiza como el numero de factores recomendados, revisando como se relacionan con variables latentes.</p>
<div class="cell">
<pre><code>## 
## Reliability analysis   
## Call: alpha(x = variables_afe)
## 
##   raw_alpha std.alpha G6(smc) average_r S/N   ase mean   sd median_r
##       0.79      0.78    0.77      0.38 3.6 0.005  2.9 0.64     0.34
## 
##     95% confidence boundaries 
##          lower alpha upper
## Feldt     0.77  0.79  0.79
## Duhachek  0.78  0.79  0.79
## 
##  Reliability if an item is dropped:
##                     raw_alpha std.alpha G6(smc) average_r S/N alpha se  var.r
## conf_gobierno            0.72      0.72    0.69      0.34 2.6   0.0067 0.0073
## conf_poder_judicial      0.72      0.72    0.69      0.34 2.6   0.0066 0.0078
## conf_partidos            0.75      0.75    0.73      0.38 3.0   0.0058 0.0124
## conf_policia             0.77      0.77    0.74      0.40 3.3   0.0055 0.0153
## conf_medios              0.78      0.78    0.76      0.42 3.6   0.0052 0.0117
## satisf_democracia        0.76      0.77    0.74      0.40 3.3   0.0056 0.0115
##                     med.r
## conf_gobierno        0.32
## conf_poder_judicial  0.31
## conf_partidos        0.36
## conf_policia         0.36
## conf_medios          0.40
## satisf_democracia    0.37
## 
##  Item statistics 
##                        n raw.r std.r r.cor r.drop mean   sd
## conf_gobierno       4324  0.80  0.78  0.75   0.65  2.9 1.05
## conf_poder_judicial 4324  0.78  0.78  0.75   0.66  3.0 0.92
## conf_partidos       4324  0.68  0.70  0.61   0.54  3.3 0.80
## conf_policia        4324  0.67  0.65  0.54   0.48  2.5 0.99
## conf_medios         4324  0.59  0.60  0.46   0.41  2.7 0.87
## satisf_democracia   4324  0.65  0.65  0.54   0.48  2.7 0.89
## 
## Non missing response frequency for each item
##                        1    2    3    4 miss
## conf_gobierno       0.13 0.22 0.28 0.37    0
## conf_poder_judicial 0.07 0.20 0.36 0.37    0
## conf_partidos       0.03 0.12 0.33 0.52    0
## conf_policia        0.19 0.32 0.31 0.18    0
## conf_medios         0.08 0.33 0.39 0.20    0
## satisf_democracia   0.11 0.29 0.42 0.18    0</code></pre>
</div>
<p>Finalmente se mide la confiabilidad de las Escalas a través del Alpha de Cronbach, midiendo una a una en las variables usadas que tan confiables son en rangos de 1 a 0.7 se consideran, valores aceptables y que son altamente confiables en lo que respecta el AFE</p>
</section>
<section id="análisis-de-conglomerados" class="level2">
<h2 class="anchored" data-anchor-id="análisis-de-conglomerados">Análisis de Conglomerados</h2>
<p>El análisis de conglomerados es un tipo de análisis que permite ver como se distribuyen los datos en grupos llamados conglomerados o clusters y como estos se agrupan usando variables cualitativas y cuantitativas, cabe destacar que los conglomerados son homegenios en su interior pero también son heterogéneos hacia el exterior.</p>
<p>Como primer paso se escogen las variables que serán utilizadas para el Análisis de Clusters</p>
<p>Como segundo paso se procede a determinar el numero optimo de cluesters a través de dos gráficos, el primero al igual que el modelo anterior se parte con el gráfico de sedimentos o llamado del codo para mostrar el numero optimo de clusters, mientras que la silueta evalúa la calidad de los clusters, midiendo que tan bien se separan los clusters, haciendo que un valor promedio alto indica una buena estructura.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Trabajo-Final-Pendola-y-Sepulveda_files/figure-html/Numero%20Optimo%20de%20Cluster-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Trabajo-Final-Pendola-y-Sepulveda_files/figure-html/Numero%20Optimo%20de%20Cluster-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Para el tercer paso, se procedió a calcular los K-means del archivo de Cluster, en otras palabras se procedió a agrupar las observación en 4 clusters distintivos, que se arman desde una semilla de casos aleatorios, esto permite entonces que la diferencia entre clusters sea la mas grande posible y aumenta la similitud dentro de un cluster</p>
<p>Con el cuarto paso ya se procedió plenamente a visualizar los resultados del clustering, se escogió una paleta de colores distinta para Cluster haciendo así mas fácil su distinción del resto</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Trabajo-Final-Pendola-y-Sepulveda_files/figure-html/Visualizacion%20del%20Cluster-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Finalmente para el Quinto se busco caracterizar los Clusters debido a que estos se encontraban muy conectados los unos con los otros, entonces se busco una forma de caracterizarlos de la mejor manera posible</p>
<div class="cell">
<pre><code>## # A tibble: 4 × 8
##   cluster     n conf_gobierno conf_judicial conf_partidos conf_medios
##   &lt;fct&gt;   &lt;int&gt;         &lt;dbl&gt;         &lt;dbl&gt;         &lt;dbl&gt;       &lt;dbl&gt;
## 1 1        1082          3.34          3.54          3.65        3.22
## 2 2        1229          2.82          3.15          3.58        2.48
## 3 3         966          1.61          1.88          2.37        2.17
## 4 4        1047          3.67          3.41          3.63        2.95
## # ℹ 2 more variables: conf_policia &lt;dbl&gt;, satis_democracia &lt;dbl&gt;</code></pre>
</div>
</section>
<section id="análisis-de-correspondencias-múltiples" class="level2">
<h2 class="anchored" data-anchor-id="análisis-de-correspondencias-múltiples">Análisis de Correspondencias Múltiples</h2>
<p>El Análisis de Correspondencias Múltiples se trata de un tipo de análisis que convierte las variables y sus resultado en coordenadas dentro de un plano, permitiendo en explorar patrones en respuestas de cuestionarios, es por ello que principalmente requiere el uso de variables de carácter categórico pues usa tablas de contingencia para producir.</p>
<p>Es por ello el primer paso fue la creación de 6 tablas de contingencia para hacer posible la producción de un análisis de correspondencias múltiples y ademas a cada tabla se le aplico una prueba de Chi-cuadrado, para evaluar la independencia de cada tabla de contingencia, todo esto usando la base datos “data_limpia_categorica”, pues los datos ya fueron convertidos a variables de carácter categórico previamente.</p>
<p>La primera Tabla es de Confianza en el Gobierno por País</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<tbody>
<tr class="odd">
<td rowspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; border-bottom: 1px solid;">Pais</td>
<td colspan="4" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal;">conf_gobierno</td>
<td rowspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; font-weight: bolder; font-style: italic; border-bottom: 1px solid; background-color: #f8f8f8;">Total</td>
</tr>
<tr class="even">
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">Mucha confianza</td>
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">Algo de confianza</td>
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">Poca confianza</td>
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">Ninguna confianza</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">Argentina</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">91</span><br>
<span style="color:#333399;">8&nbsp;%</span><br>
<span style="color:#339933;">15.9&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">297</span><br>
<span style="color:#333399;">26.2&nbsp;%</span><br>
<span style="color:#339933;">31.5&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">311</span><br>
<span style="color:#333399;">27.4&nbsp;%</span><br>
<span style="color:#339933;">25.5&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">435</span><br>
<span style="color:#333399;">38.4&nbsp;%</span><br>
<span style="color:#339933;">27.3&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; background-color: #f8f8f8;"><span style="color:black;">1134</span><br>
<span style="color:#333399;">100&nbsp;%</span><br>
<span style="color:#339933;">26.2&nbsp;%</span></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">Chile</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">127</span><br>
<span style="color:#333399;">11&nbsp;%</span><br>
<span style="color:#339933;">22.2&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">317</span><br>
<span style="color:#333399;">27.5&nbsp;%</span><br>
<span style="color:#339933;">33.6&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">396</span><br>
<span style="color:#333399;">34.3&nbsp;%</span><br>
<span style="color:#339933;">32.5&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">314</span><br>
<span style="color:#333399;">27.2&nbsp;%</span><br>
<span style="color:#339933;">19.7&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; background-color: #f8f8f8;"><span style="color:black;">1154</span><br>
<span style="color:#333399;">100&nbsp;%</span><br>
<span style="color:#339933;">26.7&nbsp;%</span></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">El Salvador</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">345</span><br>
<span style="color:#333399;">38.8&nbsp;%</span><br>
<span style="color:#339933;">60.4&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">239</span><br>
<span style="color:#333399;">26.9&nbsp;%</span><br>
<span style="color:#339933;">25.3&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">209</span><br>
<span style="color:#333399;">23.5&nbsp;%</span><br>
<span style="color:#339933;">17.1&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">96</span><br>
<span style="color:#333399;">10.8&nbsp;%</span><br>
<span style="color:#339933;">6&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; background-color: #f8f8f8;"><span style="color:black;">889</span><br>
<span style="color:#333399;">100&nbsp;%</span><br>
<span style="color:#339933;">20.6&nbsp;%</span></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">Peru</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">8</span><br>
<span style="color:#333399;">0.7&nbsp;%</span><br>
<span style="color:#339933;">1.4&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">90</span><br>
<span style="color:#333399;">7.8&nbsp;%</span><br>
<span style="color:#339933;">9.5&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">303</span><br>
<span style="color:#333399;">26.4&nbsp;%</span><br>
<span style="color:#339933;">24.9&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">746</span><br>
<span style="color:#333399;">65&nbsp;%</span><br>
<span style="color:#339933;">46.9&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; background-color: #f8f8f8;"><span style="color:black;">1147</span><br>
<span style="color:#333399;">100&nbsp;%</span><br>
<span style="color:#339933;">26.5&nbsp;%</span></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8; font-weight: bolder; font-style: italic; vertical-align: middle;">Total</td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8;"><span style="color:black;">571</span><br>
<span style="color:#333399;">13.2&nbsp;%</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8;"><span style="color:black;">943</span><br>
<span style="color:#333399;">21.8&nbsp;%</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8;"><span style="color:black;">1219</span><br>
<span style="color:#333399;">28.2&nbsp;%</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8;"><span style="color:black;">1591</span><br>
<span style="color:#333399;">36.8&nbsp;%</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8;"><span style="color:black;">4324</span><br>
<span style="color:#333399;">100&nbsp;%</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<div class="tabwid"><style>.cl-488cea56{table-layout:auto;}.cl-487d5172{font-family:'Times New Roman';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-487d5186{font-family:'Times New Roman';font-size:12pt;font-weight:normal;font-style:italic;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-4881fa92{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 2;background-color:transparent;}.cl-4881faa6{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 2;background-color:transparent;}.cl-488228e6{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-488228fa{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-48822904{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-488cea56"><thead><tr style="overflow-wrap:break-word;"><th class="cl-488228e6"><p class="cl-4881fa92"><span class="cl-487d5172">statistic</span></p></th><th class="cl-488228e6"><p class="cl-4881fa92"><span class="cl-487d5186">p</span></p></th><th class="cl-488228e6"><p class="cl-4881fa92"><span class="cl-487d5172">parameter</span></p></th><th class="cl-488228e6"><p class="cl-4881fa92"><span class="cl-487d5172">Method</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-488228fa"><p class="cl-4881faa6"><span class="cl-487d5172">1,209.72</span></p></td><td class="cl-48822904"><p class="cl-4881fa92"><span class="cl-487d5172">&lt; .001***</span></p></td><td class="cl-48822904"><p class="cl-4881fa92"><span class="cl-487d5172">9</span></p></td><td class="cl-48822904"><p class="cl-4881fa92"><span class="cl-487d5172">Pearson's Chi-squared test</span></p></td></tr></tbody></table></div>
</div>
</div>
<p>La Segunda Tabla es de País por Confianza en el poder Judicial</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<tbody>
<tr class="odd">
<td rowspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; border-bottom: 1px solid;">Pais</td>
<td colspan="4" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal;">conf_poder_judicial</td>
<td rowspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; font-weight: bolder; font-style: italic; border-bottom: 1px solid; background-color: #f8f8f8;">Total</td>
</tr>
<tr class="even">
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">Mucha confianza</td>
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">Algo de confianza</td>
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">Poca confianza</td>
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">Ninguna confianza</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">Argentina</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">37</span><br>
<span style="color:#333399;">3.3&nbsp;%</span><br>
<span style="color:#339933;">12.1&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">228</span><br>
<span style="color:#333399;">20.1&nbsp;%</span><br>
<span style="color:#339933;">26.2&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">472</span><br>
<span style="color:#333399;">41.6&nbsp;%</span><br>
<span style="color:#339933;">30.3&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">397</span><br>
<span style="color:#333399;">35&nbsp;%</span><br>
<span style="color:#339933;">25&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; background-color: #f8f8f8;"><span style="color:black;">1134</span><br>
<span style="color:#333399;">100&nbsp;%</span><br>
<span style="color:#339933;">26.2&nbsp;%</span></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">Chile</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">41</span><br>
<span style="color:#333399;">3.6&nbsp;%</span><br>
<span style="color:#339933;">13.4&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">184</span><br>
<span style="color:#333399;">15.9&nbsp;%</span><br>
<span style="color:#339933;">21.1&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">446</span><br>
<span style="color:#333399;">38.6&nbsp;%</span><br>
<span style="color:#339933;">28.6&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">483</span><br>
<span style="color:#333399;">41.9&nbsp;%</span><br>
<span style="color:#339933;">30.4&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; background-color: #f8f8f8;"><span style="color:black;">1154</span><br>
<span style="color:#333399;">100&nbsp;%</span><br>
<span style="color:#339933;">26.7&nbsp;%</span></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">El Salvador</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">204</span><br>
<span style="color:#333399;">22.9&nbsp;%</span><br>
<span style="color:#339933;">66.7&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">267</span><br>
<span style="color:#333399;">30&nbsp;%</span><br>
<span style="color:#339933;">30.7&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">288</span><br>
<span style="color:#333399;">32.4&nbsp;%</span><br>
<span style="color:#339933;">18.5&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">130</span><br>
<span style="color:#333399;">14.6&nbsp;%</span><br>
<span style="color:#339933;">8.2&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; background-color: #f8f8f8;"><span style="color:black;">889</span><br>
<span style="color:#333399;">100&nbsp;%</span><br>
<span style="color:#339933;">20.6&nbsp;%</span></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">Peru</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">24</span><br>
<span style="color:#333399;">2.1&nbsp;%</span><br>
<span style="color:#339933;">7.8&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">191</span><br>
<span style="color:#333399;">16.7&nbsp;%</span><br>
<span style="color:#339933;">22&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">351</span><br>
<span style="color:#333399;">30.6&nbsp;%</span><br>
<span style="color:#339933;">22.5&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">581</span><br>
<span style="color:#333399;">50.7&nbsp;%</span><br>
<span style="color:#339933;">36.5&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; background-color: #f8f8f8;"><span style="color:black;">1147</span><br>
<span style="color:#333399;">100&nbsp;%</span><br>
<span style="color:#339933;">26.5&nbsp;%</span></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8; font-weight: bolder; font-style: italic; vertical-align: middle;">Total</td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8;"><span style="color:black;">306</span><br>
<span style="color:#333399;">7.1&nbsp;%</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8;"><span style="color:black;">870</span><br>
<span style="color:#333399;">20.1&nbsp;%</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8;"><span style="color:black;">1557</span><br>
<span style="color:#333399;">36&nbsp;%</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8;"><span style="color:black;">1591</span><br>
<span style="color:#333399;">36.8&nbsp;%</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8;"><span style="color:black;">4324</span><br>
<span style="color:#333399;">100&nbsp;%</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<div class="tabwid"><style>.cl-48babec2{table-layout:auto;}.cl-48b1c696{font-family:'Times New Roman';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-48b1c6aa{font-family:'Times New Roman';font-size:12pt;font-weight:normal;font-style:italic;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-48b58420{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 2;background-color:transparent;}.cl-48b58434{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 2;background-color:transparent;}.cl-48b5a46e{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-48b5a478{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-48b5a479{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-48babec2"><thead><tr style="overflow-wrap:break-word;"><th class="cl-48b5a46e"><p class="cl-48b58420"><span class="cl-48b1c696">statistic</span></p></th><th class="cl-48b5a46e"><p class="cl-48b58420"><span class="cl-48b1c6aa">p</span></p></th><th class="cl-48b5a46e"><p class="cl-48b58420"><span class="cl-48b1c696">parameter</span></p></th><th class="cl-48b5a46e"><p class="cl-48b58420"><span class="cl-48b1c696">Method</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-48b5a478"><p class="cl-48b58434"><span class="cl-48b1c696">672.86</span></p></td><td class="cl-48b5a479"><p class="cl-48b58420"><span class="cl-48b1c696">&lt; .001***</span></p></td><td class="cl-48b5a479"><p class="cl-48b58420"><span class="cl-48b1c696">9</span></p></td><td class="cl-48b5a479"><p class="cl-48b58420"><span class="cl-48b1c696">Pearson's Chi-squared test</span></p></td></tr></tbody></table></div>
</div>
</div>
<p>La Tercera Tabla es de País por Confianza en el Partidos Políticos</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<tbody>
<tr class="odd">
<td rowspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; border-bottom: 1px solid;">Pais</td>
<td colspan="4" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal;">conf_partidos</td>
<td rowspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; font-weight: bolder; font-style: italic; border-bottom: 1px solid; background-color: #f8f8f8;">Total</td>
</tr>
<tr class="even">
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">Mucha confianza</td>
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">Algo de confianza</td>
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">Poca confianza</td>
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">Ninguna confianza</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">Argentina</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">26</span><br>
<span style="color:#333399;">2.3&nbsp;%</span><br>
<span style="color:#339933;">20.5&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">181</span><br>
<span style="color:#333399;">16&nbsp;%</span><br>
<span style="color:#339933;">34&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">401</span><br>
<span style="color:#333399;">35.4&nbsp;%</span><br>
<span style="color:#339933;">28.5&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">526</span><br>
<span style="color:#333399;">46.4&nbsp;%</span><br>
<span style="color:#339933;">23.3&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; background-color: #f8f8f8;"><span style="color:black;">1134</span><br>
<span style="color:#333399;">100&nbsp;%</span><br>
<span style="color:#339933;">26.2&nbsp;%</span></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">Chile</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">26</span><br>
<span style="color:#333399;">2.3&nbsp;%</span><br>
<span style="color:#339933;">20.5&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">122</span><br>
<span style="color:#333399;">10.6&nbsp;%</span><br>
<span style="color:#339933;">22.9&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">364</span><br>
<span style="color:#333399;">31.5&nbsp;%</span><br>
<span style="color:#339933;">25.9&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">642</span><br>
<span style="color:#333399;">55.6&nbsp;%</span><br>
<span style="color:#339933;">28.4&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; background-color: #f8f8f8;"><span style="color:black;">1154</span><br>
<span style="color:#333399;">100&nbsp;%</span><br>
<span style="color:#339933;">26.7&nbsp;%</span></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">El Salvador</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">68</span><br>
<span style="color:#333399;">7.6&nbsp;%</span><br>
<span style="color:#339933;">53.5&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">134</span><br>
<span style="color:#333399;">15.1&nbsp;%</span><br>
<span style="color:#339933;">25.2&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">331</span><br>
<span style="color:#333399;">37.2&nbsp;%</span><br>
<span style="color:#339933;">23.5&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">356</span><br>
<span style="color:#333399;">40&nbsp;%</span><br>
<span style="color:#339933;">15.8&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; background-color: #f8f8f8;"><span style="color:black;">889</span><br>
<span style="color:#333399;">100&nbsp;%</span><br>
<span style="color:#339933;">20.6&nbsp;%</span></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">Peru</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">7</span><br>
<span style="color:#333399;">0.6&nbsp;%</span><br>
<span style="color:#339933;">5.5&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">95</span><br>
<span style="color:#333399;">8.3&nbsp;%</span><br>
<span style="color:#339933;">17.9&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">311</span><br>
<span style="color:#333399;">27.1&nbsp;%</span><br>
<span style="color:#339933;">22.1&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">734</span><br>
<span style="color:#333399;">64&nbsp;%</span><br>
<span style="color:#339933;">32.5&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; background-color: #f8f8f8;"><span style="color:black;">1147</span><br>
<span style="color:#333399;">100&nbsp;%</span><br>
<span style="color:#339933;">26.5&nbsp;%</span></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8; font-weight: bolder; font-style: italic; vertical-align: middle;">Total</td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8;"><span style="color:black;">127</span><br>
<span style="color:#333399;">2.9&nbsp;%</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8;"><span style="color:black;">532</span><br>
<span style="color:#333399;">12.3&nbsp;%</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8;"><span style="color:black;">1407</span><br>
<span style="color:#333399;">32.5&nbsp;%</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8;"><span style="color:black;">2258</span><br>
<span style="color:#333399;">52.2&nbsp;%</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8;"><span style="color:black;">4324</span><br>
<span style="color:#333399;">100&nbsp;%</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<div class="tabwid"><style>.cl-48da8d74{table-layout:auto;}.cl-48d12f9a{font-family:'Times New Roman';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-48d12fa4{font-family:'Times New Roman';font-size:12pt;font-weight:normal;font-style:italic;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-48d4e13a{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 2;background-color:transparent;}.cl-48d4e14e{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 2;background-color:transparent;}.cl-48d5115a{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-48d51164{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-48d5116e{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-48da8d74"><thead><tr style="overflow-wrap:break-word;"><th class="cl-48d5115a"><p class="cl-48d4e13a"><span class="cl-48d12f9a">statistic</span></p></th><th class="cl-48d5115a"><p class="cl-48d4e13a"><span class="cl-48d12fa4">p</span></p></th><th class="cl-48d5115a"><p class="cl-48d4e13a"><span class="cl-48d12f9a">parameter</span></p></th><th class="cl-48d5115a"><p class="cl-48d4e13a"><span class="cl-48d12f9a">Method</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-48d51164"><p class="cl-48d4e14e"><span class="cl-48d12f9a">212.72</span></p></td><td class="cl-48d5116e"><p class="cl-48d4e13a"><span class="cl-48d12f9a">&lt; .001***</span></p></td><td class="cl-48d5116e"><p class="cl-48d4e13a"><span class="cl-48d12f9a">9</span></p></td><td class="cl-48d5116e"><p class="cl-48d4e13a"><span class="cl-48d12f9a">Pearson's Chi-squared test</span></p></td></tr></tbody></table></div>
</div>
</div>
<p>La Cuarta Tabla es de País por Confianza en la Policía</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<tbody>
<tr class="odd">
<td rowspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; border-bottom: 1px solid;">Pais</td>
<td colspan="4" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal;">conf_policia</td>
<td rowspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; font-weight: bolder; font-style: italic; border-bottom: 1px solid; background-color: #f8f8f8;">Total</td>
</tr>
<tr class="even">
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">Mucha confianza</td>
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">Algo de confianza</td>
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">Poca confianza</td>
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">Ninguna confianza</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">Argentina</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">111</span><br>
<span style="color:#333399;">9.8&nbsp;%</span><br>
<span style="color:#339933;">13.4&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">348</span><br>
<span style="color:#333399;">30.7&nbsp;%</span><br>
<span style="color:#339933;">24.9&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">405</span><br>
<span style="color:#333399;">35.7&nbsp;%</span><br>
<span style="color:#339933;">30.6&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">270</span><br>
<span style="color:#333399;">23.8&nbsp;%</span><br>
<span style="color:#339933;">34.9&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; background-color: #f8f8f8;"><span style="color:black;">1134</span><br>
<span style="color:#333399;">100&nbsp;%</span><br>
<span style="color:#339933;">26.2&nbsp;%</span></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">Chile</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">333</span><br>
<span style="color:#333399;">28.9&nbsp;%</span><br>
<span style="color:#339933;">40.3&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">454</span><br>
<span style="color:#333399;">39.3&nbsp;%</span><br>
<span style="color:#339933;">32.5&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">261</span><br>
<span style="color:#333399;">22.6&nbsp;%</span><br>
<span style="color:#339933;">19.7&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">106</span><br>
<span style="color:#333399;">9.2&nbsp;%</span><br>
<span style="color:#339933;">13.7&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; background-color: #f8f8f8;"><span style="color:black;">1154</span><br>
<span style="color:#333399;">100&nbsp;%</span><br>
<span style="color:#339933;">26.7&nbsp;%</span></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">El Salvador</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">306</span><br>
<span style="color:#333399;">34.4&nbsp;%</span><br>
<span style="color:#339933;">37&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">273</span><br>
<span style="color:#333399;">30.7&nbsp;%</span><br>
<span style="color:#339933;">19.5&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">227</span><br>
<span style="color:#333399;">25.5&nbsp;%</span><br>
<span style="color:#339933;">17.1&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">83</span><br>
<span style="color:#333399;">9.3&nbsp;%</span><br>
<span style="color:#339933;">10.7&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; background-color: #f8f8f8;"><span style="color:black;">889</span><br>
<span style="color:#333399;">100&nbsp;%</span><br>
<span style="color:#339933;">20.6&nbsp;%</span></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">Peru</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">76</span><br>
<span style="color:#333399;">6.6&nbsp;%</span><br>
<span style="color:#339933;">9.2&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">324</span><br>
<span style="color:#333399;">28.2&nbsp;%</span><br>
<span style="color:#339933;">23.2&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">432</span><br>
<span style="color:#333399;">37.7&nbsp;%</span><br>
<span style="color:#339933;">32.6&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">315</span><br>
<span style="color:#333399;">27.5&nbsp;%</span><br>
<span style="color:#339933;">40.7&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; background-color: #f8f8f8;"><span style="color:black;">1147</span><br>
<span style="color:#333399;">100&nbsp;%</span><br>
<span style="color:#339933;">26.5&nbsp;%</span></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8; font-weight: bolder; font-style: italic; vertical-align: middle;">Total</td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8;"><span style="color:black;">826</span><br>
<span style="color:#333399;">19.1&nbsp;%</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8;"><span style="color:black;">1399</span><br>
<span style="color:#333399;">32.4&nbsp;%</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8;"><span style="color:black;">1325</span><br>
<span style="color:#333399;">30.6&nbsp;%</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8;"><span style="color:black;">774</span><br>
<span style="color:#333399;">17.9&nbsp;%</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8;"><span style="color:black;">4324</span><br>
<span style="color:#333399;">100&nbsp;%</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<div class="tabwid"><style>.cl-48f97f0e{table-layout:auto;}.cl-48f031e2{font-family:'Times New Roman';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-48f031ec{font-family:'Times New Roman';font-size:12pt;font-weight:normal;font-style:italic;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-48f4356c{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 2;background-color:transparent;}.cl-48f43576{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 2;background-color:transparent;}.cl-48f456be{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-48f456c8{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-48f456c9{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-48f97f0e"><thead><tr style="overflow-wrap:break-word;"><th class="cl-48f456be"><p class="cl-48f4356c"><span class="cl-48f031e2">statistic</span></p></th><th class="cl-48f456be"><p class="cl-48f4356c"><span class="cl-48f031ec">p</span></p></th><th class="cl-48f456be"><p class="cl-48f4356c"><span class="cl-48f031e2">parameter</span></p></th><th class="cl-48f456be"><p class="cl-48f4356c"><span class="cl-48f031e2">Method</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-48f456c8"><p class="cl-48f43576"><span class="cl-48f031e2">562.65</span></p></td><td class="cl-48f456c9"><p class="cl-48f4356c"><span class="cl-48f031e2">&lt; .001***</span></p></td><td class="cl-48f456c9"><p class="cl-48f4356c"><span class="cl-48f031e2">9</span></p></td><td class="cl-48f456c9"><p class="cl-48f4356c"><span class="cl-48f031e2">Pearson's Chi-squared test</span></p></td></tr></tbody></table></div>
</div>
</div>
<p>La Quinta Tabla es de País por Confianza en los Medios de Comunicación</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<tbody>
<tr class="odd">
<td rowspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; border-bottom: 1px solid;">Pais</td>
<td colspan="4" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal;">conf_medios</td>
<td rowspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; font-weight: bolder; font-style: italic; border-bottom: 1px solid; background-color: #f8f8f8;">Total</td>
</tr>
<tr class="even">
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">Mucha confianza</td>
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">Algo de confianza</td>
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">Poca confianza</td>
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">Ninguna confianza</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">Argentina</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">50</span><br>
<span style="color:#333399;">4.4&nbsp;%</span><br>
<span style="color:#339933;">14.9&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">402</span><br>
<span style="color:#333399;">35.4&nbsp;%</span><br>
<span style="color:#339933;">28.1&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">459</span><br>
<span style="color:#333399;">40.5&nbsp;%</span><br>
<span style="color:#339933;">26.9&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">223</span><br>
<span style="color:#333399;">19.7&nbsp;%</span><br>
<span style="color:#339933;">26.1&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; background-color: #f8f8f8;"><span style="color:black;">1134</span><br>
<span style="color:#333399;">100&nbsp;%</span><br>
<span style="color:#339933;">26.2&nbsp;%</span></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">Chile</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">49</span><br>
<span style="color:#333399;">4.2&nbsp;%</span><br>
<span style="color:#339933;">14.6&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">455</span><br>
<span style="color:#333399;">39.4&nbsp;%</span><br>
<span style="color:#339933;">31.8&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">452</span><br>
<span style="color:#333399;">39.2&nbsp;%</span><br>
<span style="color:#339933;">26.5&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">198</span><br>
<span style="color:#333399;">17.2&nbsp;%</span><br>
<span style="color:#339933;">23.2&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; background-color: #f8f8f8;"><span style="color:black;">1154</span><br>
<span style="color:#333399;">100&nbsp;%</span><br>
<span style="color:#339933;">26.7&nbsp;%</span></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">El Salvador</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">166</span><br>
<span style="color:#333399;">18.7&nbsp;%</span><br>
<span style="color:#339933;">49.6&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">248</span><br>
<span style="color:#333399;">27.9&nbsp;%</span><br>
<span style="color:#339933;">17.4&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">354</span><br>
<span style="color:#333399;">39.8&nbsp;%</span><br>
<span style="color:#339933;">20.8&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">121</span><br>
<span style="color:#333399;">13.6&nbsp;%</span><br>
<span style="color:#339933;">14.2&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; background-color: #f8f8f8;"><span style="color:black;">889</span><br>
<span style="color:#333399;">100&nbsp;%</span><br>
<span style="color:#339933;">20.6&nbsp;%</span></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">Peru</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">70</span><br>
<span style="color:#333399;">6.1&nbsp;%</span><br>
<span style="color:#339933;">20.9&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">324</span><br>
<span style="color:#333399;">28.2&nbsp;%</span><br>
<span style="color:#339933;">22.7&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">440</span><br>
<span style="color:#333399;">38.4&nbsp;%</span><br>
<span style="color:#339933;">25.8&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">313</span><br>
<span style="color:#333399;">27.3&nbsp;%</span><br>
<span style="color:#339933;">36.6&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; background-color: #f8f8f8;"><span style="color:black;">1147</span><br>
<span style="color:#333399;">100&nbsp;%</span><br>
<span style="color:#339933;">26.5&nbsp;%</span></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8; font-weight: bolder; font-style: italic; vertical-align: middle;">Total</td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8;"><span style="color:black;">335</span><br>
<span style="color:#333399;">7.7&nbsp;%</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8;"><span style="color:black;">1429</span><br>
<span style="color:#333399;">33&nbsp;%</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8;"><span style="color:black;">1705</span><br>
<span style="color:#333399;">39.4&nbsp;%</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8;"><span style="color:black;">855</span><br>
<span style="color:#333399;">19.8&nbsp;%</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8;"><span style="color:black;">4324</span><br>
<span style="color:#333399;">100&nbsp;%</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<div class="tabwid"><style>.cl-491846f0{table-layout:auto;}.cl-490ee196{font-family:'Times New Roman';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-490ee1a0{font-family:'Times New Roman';font-size:12pt;font-weight:normal;font-style:italic;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-49126794{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 2;background-color:transparent;}.cl-491267bc{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 2;background-color:transparent;}.cl-49128ca6{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-49128cb0{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-49128cba{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-491846f0"><thead><tr style="overflow-wrap:break-word;"><th class="cl-49128ca6"><p class="cl-49126794"><span class="cl-490ee196">statistic</span></p></th><th class="cl-49128ca6"><p class="cl-49126794"><span class="cl-490ee1a0">p</span></p></th><th class="cl-49128ca6"><p class="cl-49126794"><span class="cl-490ee196">parameter</span></p></th><th class="cl-49128ca6"><p class="cl-49126794"><span class="cl-490ee196">Method</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-49128cb0"><p class="cl-491267bc"><span class="cl-490ee196">261.41</span></p></td><td class="cl-49128cba"><p class="cl-49126794"><span class="cl-490ee196">&lt; .001***</span></p></td><td class="cl-49128cba"><p class="cl-49126794"><span class="cl-490ee196">9</span></p></td><td class="cl-49128cba"><p class="cl-49126794"><span class="cl-490ee196">Pearson's Chi-squared test</span></p></td></tr></tbody></table></div>
</div>
</div>
<p>La Sexta Tabla es de País por Satisfacción con la Democracia</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<tbody>
<tr class="odd">
<td rowspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; border-bottom: 1px solid;">Pais</td>
<td colspan="4" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal;">satisf_democracia</td>
<td rowspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; font-weight: bolder; font-style: italic; border-bottom: 1px solid; background-color: #f8f8f8;">Total</td>
</tr>
<tr class="even">
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">Algo Satisfecho</td>
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">Muy Satisfecho</td>
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">Nada Satisfecho</td>
<td style="text-align: center; border-bottom: 1px solid; padding: 0.2cm;">Poca Satisfecho</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">Argentina</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">458</span><br>
<span style="color:#333399;">40.4&nbsp;%</span><br>
<span style="color:#339933;">36.3&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">83</span><br>
<span style="color:#333399;">7.3&nbsp;%</span><br>
<span style="color:#339933;">17.4&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">120</span><br>
<span style="color:#333399;">10.6&nbsp;%</span><br>
<span style="color:#339933;">15.7&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">473</span><br>
<span style="color:#333399;">41.7&nbsp;%</span><br>
<span style="color:#339933;">25.9&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; background-color: #f8f8f8;"><span style="color:black;">1134</span><br>
<span style="color:#333399;">100&nbsp;%</span><br>
<span style="color:#339933;">26.2&nbsp;%</span></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">Chile</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">453</span><br>
<span style="color:#333399;">39.3&nbsp;%</span><br>
<span style="color:#339933;">36&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">58</span><br>
<span style="color:#333399;">5&nbsp;%</span><br>
<span style="color:#339933;">12.2&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">133</span><br>
<span style="color:#333399;">11.5&nbsp;%</span><br>
<span style="color:#339933;">17.5&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">510</span><br>
<span style="color:#333399;">44.2&nbsp;%</span><br>
<span style="color:#339933;">27.9&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; background-color: #f8f8f8;"><span style="color:black;">1154</span><br>
<span style="color:#333399;">100&nbsp;%</span><br>
<span style="color:#339933;">26.7&nbsp;%</span></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">El Salvador</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">276</span><br>
<span style="color:#333399;">31&nbsp;%</span><br>
<span style="color:#339933;">21.9&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">293</span><br>
<span style="color:#333399;">33&nbsp;%</span><br>
<span style="color:#339933;">61.4&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">68</span><br>
<span style="color:#333399;">7.6&nbsp;%</span><br>
<span style="color:#339933;">8.9&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">252</span><br>
<span style="color:#333399;">28.3&nbsp;%</span><br>
<span style="color:#339933;">13.8&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; background-color: #f8f8f8;"><span style="color:black;">889</span><br>
<span style="color:#333399;">100&nbsp;%</span><br>
<span style="color:#339933;">20.6&nbsp;%</span></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: middle;">Peru</td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">73</span><br>
<span style="color:#333399;">6.4&nbsp;%</span><br>
<span style="color:#339933;">5.8&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">43</span><br>
<span style="color:#333399;">3.7&nbsp;%</span><br>
<span style="color:#339933;">9&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">441</span><br>
<span style="color:#333399;">38.4&nbsp;%</span><br>
<span style="color:#339933;">57.9&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm;"><span style="color:black;">590</span><br>
<span style="color:#333399;">51.4&nbsp;%</span><br>
<span style="color:#339933;">32.3&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; background-color: #f8f8f8;"><span style="color:black;">1147</span><br>
<span style="color:#333399;">100&nbsp;%</span><br>
<span style="color:#339933;">26.5&nbsp;%</span></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8; font-weight: bolder; font-style: italic; vertical-align: middle;">Total</td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8;"><span style="color:black;">1260</span><br>
<span style="color:#333399;">29.1&nbsp;%</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8;"><span style="color:black;">477</span><br>
<span style="color:#333399;">11&nbsp;%</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8;"><span style="color:black;">762</span><br>
<span style="color:#333399;">17.6&nbsp;%</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8;"><span style="color:black;">1825</span><br>
<span style="color:#333399;">42.2&nbsp;%</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
<td style="text-align: center; padding: 0.2cm; border-bottom: double; background-color: #f8f8f8;"><span style="color:black;">4324</span><br>
<span style="color:#333399;">100&nbsp;%</span><br>
<span style="color:#339933;">100&nbsp;%</span></td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<div class="tabwid"><style>.cl-4944a57e{table-layout:auto;}.cl-49391fe2{font-family:'Times New Roman';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-49391ff6{font-family:'Times New Roman';font-size:12pt;font-weight:normal;font-style:italic;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-493d972a{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 2;background-color:transparent;}.cl-493d9734{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 2;background-color:transparent;}.cl-493dbbd8{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-493dbbec{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-493dbbed{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-4944a57e"><thead><tr style="overflow-wrap:break-word;"><th class="cl-493dbbd8"><p class="cl-493d972a"><span class="cl-49391fe2">statistic</span></p></th><th class="cl-493dbbd8"><p class="cl-493d972a"><span class="cl-49391ff6">p</span></p></th><th class="cl-493dbbd8"><p class="cl-493d972a"><span class="cl-49391fe2">parameter</span></p></th><th class="cl-493dbbd8"><p class="cl-493d972a"><span class="cl-49391fe2">Method</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-493dbbec"><p class="cl-493d9734"><span class="cl-49391fe2">1,243.02</span></p></td><td class="cl-493dbbed"><p class="cl-493d972a"><span class="cl-49391fe2">&lt; .001***</span></p></td><td class="cl-493dbbed"><p class="cl-493d972a"><span class="cl-49391fe2">9</span></p></td><td class="cl-493dbbed"><p class="cl-493d972a"><span class="cl-49391fe2">Pearson's Chi-squared test</span></p></td></tr></tbody></table></div>
</div>
</div>
<p>Como siguiente paso se procedió a realizar el análisis de correspondencias múltiples usando la base de datos de “data_limpia_categorica”</p>
<p>Como tercer paso se busco medir la varianza de las variables del AMC, para saber cuantas dimensiones reales ha y que retener y ademas para medir que tan importantes son</p>
<div class="cell">
<pre><code>##        eigenvalue variance.percent cumulative.variance.percent
## Dim.1   0.4618447        15.394824                    15.39482
## Dim.2   0.3194973        10.649911                    26.04474
## Dim.3   0.2346821         7.822735                    33.86747
## Dim.4   0.1765768         5.885893                    39.75336
## Dim.5   0.1637475         5.458251                    45.21161
## Dim.6   0.1447382         4.824608                    50.03622
## Dim.7   0.1397008         4.656692                    54.69291
## Dim.8   0.1328577         4.428589                    59.12150
## Dim.9   0.1258701         4.195671                    63.31717
## Dim.10  0.1222182         4.073939                    67.39111</code></pre>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Trabajo-Final-Pendola-y-Sepulveda_files/figure-html/Eigen%20values-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Como paso final se hizo un gráfico de disperción para ver claramente en que sector se agrupaban las variables seleccionadas dentro del plano Cartesiano</p>
<div class="cell" data-cho="false">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_mca_var</span>(ACM, <span class="co">#objeto tipo lista con resultados mca</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">col.var =</span> <span class="st">"contrib"</span>, <span class="co">#definición de los colores a partir del valor cos2</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">gradient.cols =</span> <span class="fu">c</span>(<span class="st">"#00AFBB"</span>, <span class="st">"#E7B800"</span>, <span class="st">"#FC4E07"</span>, <span class="st">"#458B74"</span>, <span class="st">"#104E8B"</span>, <span class="st">"#FFFF00"</span>), <span class="co">#definición de la paleta de colores</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">repel =</span> <span class="cn">TRUE</span>, <span class="co"># evitar solapamientos de etiquetas,</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">max.overlaps =</span> <span class="st">"ggrepel.max.overlaps"</span>, <span class="co">#aumentar el tamaño de solapamientos</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">ggtheme =</span> <span class="fu">theme_minimal</span>())</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Trabajo-Final-Pendola-y-Sepulveda_files/figure-html/Grafico%20de%20las%20Dispersiones-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="resultados" class="level1">
<h1>Resultados</h1>
<section id="análisis-factorial-exploratorio" class="level2">
<h2 class="anchored" data-anchor-id="análisis-factorial-exploratorio">Análisis Factorial Exploratorio</h2>
<p>El análisis factorial exploratorio permitió identificar la estructura subyacente de las percepciones de confianza institucional en los cuatro países estudiados. Los indicadores previos mostraron que el análisis era estadísticamente adecuado: el índice KMO fue de 0.82, considerado meritorio, y el test de esfericidad de Bartlett resultó altamente significativo (χ² = 6839.19, p &lt; 0.001), indicando que las correlaciones entre las variables son suficientes para extraer factores comunes.</p>
<p>La solución factorial final extrajo tres factores mediante el método minres y rotación varimax. El primer factor agrupó confiabilidad en el gobierno y satisfacción con la democracia, conformando una dimensión de legitimidad política central, es decir, una evaluación global del funcionamiento democrático y del desempeño gubernamental. El segundo factor estuvo dominado por la confianza en los partidos políticos, con una carga factorial de 0.936, lo que confirma que este tipo de institución opera como un componente independiente dentro del mapa de la confianza ciudadana, consistente con la literatura sobre desafección partidaria en la región. El tercer factor agrupó la confianza en la policía, los medios de comunicación y el poder judicial, conformando una dimensión de orden público y comunicación, que refleja percepciones sobre instituciones encargadas del control social y de la producción y transmisión de información. Cabe destacar que la satisfacción con la democracia mostró cargas más dispersas, lo que sugiere que, aunque se relaciona con la evaluación del gobierno, no constituye una dimensión independiente.</p>
<p>En términos de confiabilidad, el modelo arrojó un alfa de Cronbach de 0.79, indicando una consistencia interna adecuada. En conjunto, el AFE evidencia que la confianza institucional es un fenómeno multidimensional, articulado en torno a evaluaciones del gobierno, del sistema de representación formal y de instituciones asociadas al orden y la comunicación&nbsp;pública.</p>
</section>
<section id="análisis-de-conglomerados-1" class="level2">
<h2 class="anchored" data-anchor-id="análisis-de-conglomerados-1">Análisis de Conglomerados</h2>
<p>Para complementar el análisis factorial, se realizó una clasificación de individuos mediante el algoritmo de k-means, con el objetivo de identificar perfiles ciudadanos según sus patrones de confianza. El número óptimo de clusters se definió en 4, basado en el método del codo —que mostró un quiebre claro en esa cantidad— y en la silueta, que aunque favorecía una solución menor, mantuvo valores aceptables para cuatro grupos. La solución mostró una cohesión interna adecuada y un tamaño de clusters equilibrado (rango: 966 a 1.229 casos).</p>
<p>Los perfiles generados ofrecen una mirada sustantiva sobre las formas de confianza en la región. El Cluster 1, con valores altos en casi todas las instituciones, representa a un grupo de institucionalistas amplios, que confían tanto en instituciones políticas como en instituciones del orden. El Cluster 2 mostró la confianza más alta en el gobierno y la mayor satisfacción con la democracia, configurando un perfil pro-gobierno y pro-régimen democrático, donde la legitimidad se articula en torno a la evaluación positiva del Ejecutivo. El Cluster 3 presentó los promedios más bajos en todas las dimensiones, constituyendo un grupo de desconfianza generalizada, caracterizado por una ruptura profunda con el sistema político y con las instituciones públicas. Finalmente, el Cluster 4 mostró niveles intermedios, con un patrón de desconfianza selectiva, especialmente hacia la policía y los medios, lo que sugiere una visión crítica pero no completamente desligada del sistema institucional.</p>
<p>En conjunto, los resultados del clustering muestran que la ciudadanía no se distribuye de manera uniforme en sus percepciones, sino que se organiza en grupos con lógicas diferenciadas de apoyo, escepticismo o rechazo institucional. Cuando estos hallazgos se leen junto al AFE, se evidencia que la estructura interna de las percepciones (dimensiones latentes) se traduce en perfiles concretos de confianza, que reflejan distintas formas de relacionamiento con el Estado, el sistema político y las instituciones de&nbsp;control&nbsp;social.</p>
</section>
<section id="analisis-conjunto" class="level2">
<h2 class="anchored" data-anchor-id="analisis-conjunto">Analisis Conjunto</h2>
<p>La aplicación conjunta del análisis factorial exploratorio (AFE), el análisis de conglomerados y el análisis de correspondencia múltiple (ACM) permite comprender con mayor profundidad la estructura y distribución de la confianza institucional en los países analizados. Cada técnica contribuye desde un ángulo distinto: el AFE identifica las dimensiones latentes que organizan el fenómeno; el clustering revela los perfiles ciudadanos que emergen de esas dimensiones; y el ACM muestra cómo las categorías de respuesta y los países se distribuyen en un espacio común. En conjunto, los tres modelos convergen en la idea de que la confianza institucional es un fenómeno multidimensional, heterogéneo y espacialmente diferenciado por país.</p>
<p>En primer lugar, el AFE evidenció la existencia de tres dimensiones diferenciadas que estructuran la confianza institucional: un eje de legitimidad política central asociado al gobierno y la evaluación democrática; un componente independiente de confianza en los partidos políticos, altamente consistente con la desafección partidaria histórica de la región; y un eje centrado en instituciones del orden y la comunicación (policía y medios). Estas dimensiones no solo muestran que la confianza no se distribuye uniformemente entre las instituciones, sino que también apuntan a distintos tipos de legitimidad: confianza política, confianza representativa y confianza socio-institucional.</p>
<p>El análisis de conglomerados profundiza esta lectura mostrando cómo estas dimensiones se expresan en grupos concretos de ciudadanos. Los cuatro clusters identificados representan formas diferenciadas de articular las dimensiones del AFE. Por ejemplo, el Cluster 1 agrupa a individuos con confianza amplia y transversal, capturando simultáneamente las tres dimensiones del AFE en niveles altos; el Cluster 2 articula altos puntajes en la dimensión de legitimidad política central, evidenciando un fuerte vínculo entre evaluación gubernamental y satisfacción democrática; el Cluster 3 expresa la versión extrema de la dimensión de desconfianza, acumulando valores bajos en todas las instituciones, especialmente en la dimensión política; y el Cluster 4 corresponde a un patrón intermedio de desconfianza selectiva, vinculado al eje de orden/comunicación identificado en el AFE. De este modo, los clusters transforman las dimensiones abstractas del AFE en perfiles sociológicos concretos, que representan modalidades reales de vínculo —o rompimiento— con las instituciones.</p>
<p>Finalmente, el ACM confirma y amplía estas relaciones mostrando que las categorías de respuesta, así como los países, se disponen en el espacio factorial siguiendo patrones coherentes con las dimensiones del AFE y los perfiles del clustering. El Eje 1 del ACM, asociado al continuo confianza–desconfianza, replica la primera dimensión del AFE y separa de manera nítida a los grupos altamente desconfiados (similar al Cluster 3) de aquellos con mayor legitimidad institucional (Clusters 1 y 2). El Eje 2 del ACM reproduce la diferenciación entre instituciones políticas y de orden/comunicación, correspondiéndose con la tercera dimensión del AFE y con los patrones selectivos del Cluster 4. Además, la posición de los países en el mapa factorial coincide con la estructura de los clusters: por ejemplo, países como Argentina y Perú tienden a alinearse con categorías de baja confianza, mientras que El Salvador aparece asociado a categorías de mayor legitimidad, especialmente en instituciones del orden.</p>
<p>Así, la convergencia entre los tres modelos permite sostener que la confianza institucional es un fenómeno no unidimensional, sino estratificado, donde la legitimidad política, la representación partidaria y la credibilidad de instituciones sociales operan de manera diferenciada. A nivel ciudadano, estas dimensiones se combinan para producir perfiles diversos de confianza, que van desde el apoyo amplio al rechazo total. A nivel comparado, la estructura de estas percepciones se organiza espacialmente según el país, reflejando contextos políticos específicos. Este diálogo metodológico entre AFE, clustering y ACM fortalece la validez de los resultados y ofrece una visión integral del carácter complejo, fragmentado y profundamente contextual de la confianza institucional en&nbsp;América Latina.</p>
</section>
</section>
<section id="conclusión" class="level1">
<h1>Conclusión</h1>
<p>Para Concluir con en primera instancia queremos destacar los principales hallazgos del trabajo, el análisis factorial exploratorio demostró que existen 3 dimensiones latentes dentro de las variables que escogimos, las cuales preliminarmente se pueden denominar como:</p>
<ul>
<li><p>Legitimidad Política del Gobierno Central</p></li>
<li><p>Confianza Partidaria</p></li>
<li><p>Confianza en Instituciones de Comunicación y Orden</p></li>
</ul>
<p>Para el análisis de Correspondencias Múltiples, se detecto que un país presenta una mayor confianza en las fuerzas del orden y ese fue el salvador, presentando que sus ciudadanos tienen mucha confianza en la fuerza policial, pero que se encuentran algo distantes pero satisfechos con el gobierno y los medios de comunicación, muy en linea de las descripciones de Morande (2008) sobre la confianza en las instituciones de la sociedad, por otra parte Chile se muestra mas bien en los terrenos neutros donde muchas las variables que lo rodean son algo de confianza o algo satisfecho al igual que Argentina y finalmente es Perú quienes sus habitantes no tienen confianza en ninguna institución o partido.</p>
<p>Para el análisis de Cluster se puede detectar 4 grupos principales, el primer de ellos se puede entender como uno de apoyo constante a las instituciones que podría se nombrado como Institucionales, el segundo grupo se puede entender que confía en el gobierno, el tercero como una desconfianza generalizada y el ultimo ya una desconfianza mas selectiva.</p>
<p>Con todo esto, entonces volvamos una vez mas a la hipótesis anteriormente planteada, la cual era “Países con presidentes de Derecha podrían mostrar mayor confianza en el gobierno a diferencia de Países con presidentes de Izquierda que mostraron índices más bajos”, encontramos que si existe una mayor confianza en las gobierno si es que quien dirige el mismo país es de derecha pero no exactamente, pues Argentina es dirigido por un presidente de derecha, pero incluso así presenta niveles bajos de confianza, entonces se podría decir que la respuesta es mas parcial que otra cosa, dando a entender que quizás exista una o mas variables que influyen en la confianza institucional, tales como el contexto sociocultural, entre otras.</p>
<p>Igualmente se quiere con esto ultimo destacar la limitación misma de la investigación realizada, pues se considero una base de datos del año pasado, quizás entonces seria recomendable usar tanto una base del mismo y convertir este estudio en uno de carácter longitudinal, ademas de considerar mas variables socialdemocracias como los ingresos, nivel de educación, genero, entre otras.</p>
<p>Igualmente en los que respecta a la confianza generalizada dentro de lo que son los espacios en gubernamentales si se requiere un trabajo mas pesado y concreto, pues sobre partidos politicos y su baja confianza requiere de nuevas formas de representación o mejores formas, sobre la confianza en el gobierno requeire una forma de comunicacion desde el oficialimso hacia la ciudadania mas efectiva</p>
</section>
<section id="bibliografia" class="level1">
<h1>Bibliografia</h1>
<p>del Campo García, M. E. (2018). Buen gobierno y confianza institucional. <em>Dilemata</em>, (27), 55–71. Recuperado a partir de <a href="https://www.dilemata.net/revista/index.php/dilemata/article/view/412000214" class="uri">https://www.dilemata.net/revista/index.php/dilemata/article/view/412000214</a></p>
<p>Estella, A. (2020): “Confianza institucional en América Latina: un análisis comparado”, Documentos de Trabajo nº 34 (2ª época), Madrid, Fundación Carolina. <a href="https://doi.org/10.33960/issn-e.1885-9119.DT34" class="uri">https://doi.org/10.33960/issn-e.1885-9119.DT34</a></p>
<p>MORALES QUIROGA, MAURICIO. (2008). Assessing Institutional Confidence in Chile: A Look from LAPOP’s Findings.&nbsp;<em>Revista de ciencia política (Santiago)</em>,&nbsp;<em>28</em>(2), 161-186.&nbsp;<a href="https://dx.doi.org/10.4067/S0718-090X2008000200007" class="uri">https://dx.doi.org/10.4067/S0718-090X2008000200007</a></p>
<p>Morales Quiroga, Mauricio. (2020). ESTALLIDO SOCIAL EN CHILE 2019: PARTICIPACIÓN, REPRESENTACIÓN, CONFIANZA INSTITUCIONAL Y ESCÁNDALOS PÚBLICOS.&nbsp;<em>Análisis Político</em>,&nbsp;<em>33</em>(98), 3-25.&nbsp;<a href="https://doi.org/10.15446/anpol.v33n98.89407" class="uri">https://doi.org/10.15446/anpol.v33n98.89407</a></p>
<p>Torcal, M., &amp; Bargsted, M. (2015). El giro a la izquierda y la confianza institucional en América Latina. <em>América Latina Hoy</em>, 70, 15-35.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>